=== larisabigvava/xml-parsing/resources/librarySchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.epam.com/librarySchema"
        xmlns:lib="http://www.epam.com/librarySchema">
    <simpleType name="genreType">
        <restriction base="string">
            <enumeration value="ROMANCE"/>
            <enumeration value="SCIENCE_FICTION"/>
            <enumeration value="HISTORICAL_FICTION"/>
            <enumeration value="FANTASY"/>
            <enumeration value="MYSTERY"/>
            <enumeration value="BIOGRAPHY"/>
        </restriction>
    </simpleType>
    <simpleType name="bookAuthorType">
        <restriction base="string">
            <pattern value="([A-Z]([a-z])*[\-\.\s]?)+"/>
            <minLength value="5"/>
            <maxLength value="255"/>
        </restriction>
    </simpleType>
    <element name="books">
        <complexType>
            <sequence>
                <element name="book" type="lib:book" minOccurs="1" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    <complexType name="book">
        <sequence>
            <element name="title" type="string"/>
            <element name="author" type="lib:bookAuthorType"/>
            <element name="genre" type="lib:genreType"/>
        </sequence>
        <attribute name="countOfPages" type="integer" use="required"/>
        <attribute name="yearOfPublishing" type="integer" use="optional"/>
    </complexType>
</schema>

=== larisabigvava/xml-parsing/resources/library.xml
<?xml version="1.0" encoding="UTF-8" ?>
<lib:books
        xmlns:lib="http://www.epam.com/librarySchema"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.epam.com/librarySchema
librarySchema.xsd">
    <book countOfPages="263">
        <title>The Godfather</title>
        <author>Mario Puzo</author>
        <genre>Mystery</genre>
    </book>
    <book countOfPages="2355" yearOfPublishing="1982">
        <title>The Hobbit</title>
        <author>J.R.R.Tolkien</author>
        <genre>Fantasy</genre>
    </book>
    <book countOfPages="500" yearOfPublishing="1980">
        <title>The Hitchhiker's Guide to the Galaxy</title>
        <author>Douglas Adams</author>
        <genre>Science_Fiction</genre>
    </book>
    <book countOfPages="305">
        <title>Pride and Prejudice</title>
        <author>Jane Austen</author>
        <genre>Romance</genre>
    </book>
    <book countOfPages="935">
        <title>War and Peace</title>
        <author>Leo Tolstoy</author>
        <genre>Historical_Fiction</genre>
    </book>
    <book countOfPages="10562" yearOfPublishing="2005">
        <title>Harry Potter series</title>
        <author>J.K.Rowling</author>
        <genre>Fantasy</genre>
    </book>
</lib:books>
